version: "3.1"

volumes:
  pihole-vol:

services:
  unbound:
    container_name: unbound
    image: dextertanyj/unbound
    restart: unless-stopped
    networks:
      default: {}
      local:
        ipv4_address: ${SUBNET_PREFIX:-172.24.0}.1
    cap_add:
      - NET_ADMIN
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "80:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "443:443/tcp"
    environment:
      - TZ=${TIMEZONE}
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      - FTLCONF_webserver_api_password=${PASSWORD:?error}
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      - FTLCONF_dns_listeningMode="all"
    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - pihole-vol:/etc/pihole
    networks:
      default: {}
      local:
        ipv4_address: ${SUBNET_PREFIX:-172.24.0}.2
    cap_add:
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    restart: unless-stopped

networks:
  default: {}
  # An internal network with static IPs for pi-hole to communicate with unbound
  local:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_PREFIX:-172.24.0}.0/24
          ip_range: ${SUBNET_PREFIX:-172.24.0}.0/24
          gateway: ${SUBNET_PREFIX:-172.24.0}.254
    internal: true
